version: 2
jobs:
  build:
    working_directory: ~/curbmapauth-js
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: NPM install
          command: |
            npm install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  deploy:
    machine: 
      enabled: true
    steps:
      - add_ssh_keys:
            fingerprints:
              - "95:95:c9:8c:b8:31:11:dd:06:11:3d:16:9c:fd:0b:96	"
      - run:
            name: Deploy over SSH
            command: |
                ssh -f $SSH_USER@$SSH_HOST "cd ~/deploy && ./runscript.sh build"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master