version: 2
jobs:
  build:
    docker:
      - image: curbmap/fedora-node:v0.0.2
    working_directory: ~/curbmapauth-js
    branches:
      only:
        - master
    steps:
      - checkout
      - run: yarn install
      - run: tar -c -v --exclude node_modules -f curbmapauth-js.tar *
      - run: bzip2 curbmapauth-js.tar
      - run: scp -r curbmapauth-js.tar.bz2 ec2-user@curbmap.com:~/tommydeploy/curbmapauth-js/
      - run: ssh ec2-user@curbmap.com "cd ~/tommydeploy && ./runscript.sh build > /dev/null &"
