version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/curbmapauth-js
    branches:
      only:
        - master
    steps:
      - checkout
      - run: yarn install
      - run: tar -c -v --exclude node_modules -f curbmapauth-js.tar *
      - run: bzip2 curbmapauth-js.tar
      - deploy:
          name: The Jester
          command:  |
            scp -o StrictHostKeyChecking=no curbmapauth-js.tar.bz2 ec2-user@curbmap.com:~/deploy/curbmapauth-js/
            ssh -o StrictHostKeyChecking=no ec2-user@curbmap.com "cd ~/deploy && ./runscript.sh build > /dev/null &"
